config/routes.rb
Bootstrapp::Application.routes.draw do

  devise_for :users

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<p>Welcome!</p>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">It's Bootstrap</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= mail_to 'finn.bacall@cs.man.ac.uk', "Contact Us" %></li>
        </ul>
        <ul class="nav pull-right">
          <li class="divider-vertical"></li>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.email %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
          <% else %>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Log in / Register <b class="caret"></b>
                </a>
                <div class="dropdown-menu" style="padding: 15px">
                  <%= render :partial => 'devise/sessions/form' %>
                  <%= link_to "Register", new_registration_path(:user) %><br />
                  <%= link_to "Forgot your password?", new_password_path(:user) %><br />
                </div>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render :partial => 'layouts/navigation' %>

<div id="main" role="main">
  <div class="container">
    <%= yield %>
  </div>
</div>

</body>
</html>